CREATE TABLE readme (
uid serial PRIMARY key NOT NULL,
common_name text,
sde_name text,
tags_guide text,
tags_sde text,
summary text,
summary_update_date text,
description text,
description_data_loc text,
data_steward text,
data_engineer text,
credits text,
genconst text,
legconst text,
update_freq text,
date_last_update text,
date_underlying_data text,
data_source text,
version text,
common_uses text,
data_quality text,
caveats text,
future_plans text,
distribution text,
contact text
);
